# doc: https://starship.rs/config/

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$line_break\
$status\
$character"""

right_format = """
${custom.git}\
$username
$hostname\
$cmd_duration\
$golang\
$python\
$rust\
$package\
$c\
$jobs\
$time\
"""

add_newline = false

[character]
format = ''

[directory]
style = "green"
read_only = " 󰌾"
truncation_length = 1  # the number of parent folders that the current directory should be truncated to.

[git_branch]
# symbol = " "
symbol = ""
format = '[\($branch\)](bold blue) '

# +-的行数
[git_metrics]
disabled = true

# info 与 character 之间是否换行
[line_break]
disabled = true

# status of last cmd, i.e. echo $?
[status]
disabled = false

[username]
style_user = 'green'
format = '$user'
show_always = true

# 当是github 的repo 时, 用个人身份, 当是公司的repo时, 用公司身份, 如果不一致, 就以红色显示出来
[custom.git]
require_repo = true
when = """
name=$(git config user.name)
git config remote.origin.url | grep github >/dev/null
if [[ $? -eq 0 ]]; then
  return $(test $name != 'ericuni')
else
  return $(test $name != 'liuqi.victor')
fi
"""
style = "red"
symbol = 'git'
command = 'git config user.name'
format = "[$output]($style)$symbol "

[hostname]
ssh_symbol = " "
format = '@$hostname '
ssh_only = false

[localip]
disabled = false
style = 'green'

[os.symbols]
Macos = " "
Ubuntu = " "
Debian = " "
Redhat = " "
Linux = " "
Unknown = " "
Windows = "󰍲 "

[shell]
disabled = true

[c]
symbol = " "

[golang]
symbol = ""
format = 'Go$version '

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[package]
symbol = "󰏗 "

[time]
disabled = false
format = '$time'

