format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$custom\
$line_break\
$status\
$character"""

right_format = """
$username\
$hostname\
$cmd_duration\
$golang\
$python\
$rust\
$package\
$c\
$jobs\
$time\
"""

add_newline = false

[character]
format = ''

[directory]
style = "green"
read_only = " 󰌾"
truncation_length = 1  # the number of parent folders that the current directory should be truncated to.

[git_branch]
# symbol = " "
symbol = ""
format = '[\($branch\)](bold blue) '

# +-的行数
[git_metrics]
disabled = true

# info 与 character 之间是否换行
[line_break]
disabled = true

# status of last cmd, i.e. echo $?
[status]
disabled = false

[username]
style_user = 'green'
format = '$user'

[hostname]
ssh_symbol = " "
format = '@$hostname '
ssh_only = false

[localip]
disabled = false
style = 'green'

[os.symbols]
Macos = " "
Ubuntu = " "
Debian = " "
Redhat = " "
Linux = " "
Unknown = " "
Windows = "󰍲 "

[shell]
disabled = true

[c]
symbol = " "

[golang]
symbol = ""
format = 'Go$version '

[nix_shell]
symbol = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[package]
symbol = "󰏗 "

[time]
disabled = false
format = '$time'
