name: Linux

on:
  push:
    paths:
      - ".github/workflows/linux.yml"
      - "env/util.sh"
      - "env/linux.sh"
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: ci pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      run: |
        sudo apt install zsh

    - name: build
      run: |
        cd env
        ./linux.sh

