name: MacOS

on:
  push:
    paths:
      - ".github/workflows/mac.yml"
      - "env/util.sh"
      - "env/mac.sh"
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: ci pipeline
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      run: |
        which zsh

    - name: build
      run: |
        cd env
        ./mac.sh

